    tokens:
      - chainName: kasplextestnet
        standard: EvmHypSynthetic
        decimals: 18
        symbol: USDT
        name: Tether USD
        addressOrDenom: "0x1B17f7A0870259288D8d9510778ef6235805CCB1"
        connections:
          - token: ethereum|bsctestnet|0x7eca5214e2A8f9a292B34E239136e3232D4a9f99
      - chainName: bsctestnet
        standard: EvmHypCollateral
        decimals: 18
        symbol: USDT
        name: Tether USD
        addressOrDenom: "0x7eca5214e2A8f9a292B34E239136e3232D4a9f99"
        collateralAddressOrDenom: "0xb97aDD318e75F98972f95323ce0A035E31784c4E"
        connections:
          - token: ethereum|kasplextestnet|0x1B17f7A0870259288D8d9510778ef6235805CCB1