owner: "0x1900c5b15268f13bb4e462f54f5edd6834c47348"
defaultIsm:
  type: trustedRelayerIsm
  relayer: "0x1900c5b15268f13bb4e462f54f5edd6834c47348"
defaultHook:
  type: merkleTreeHook
requiredHook:
  owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  type: interchainGasPaymaster
  beneficiary: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  oracleKey: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  overhead:
    bsctestnet: 75000
    igratestnet: 75000
  oracleConfig:
    bsctestnet:
      gasPrice: "100000000"
      tokenExchangeRate: "11000000000"
      tokenDecimals: 18
proxyAdmin:
  owner: "0x1900c5b15268f13bb4e462f54f5edd6834c47348"
