defaultHook:
  address: "0x7DA07bC8f8002A3b864a2C3E9994B2eaf4a7999C"
  type: merkleTreeHook
defaultIsm:
  address: "0xe7386D8B5bfDbC571bf0508687DE06552E4d1c95"
  relayer: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  type: trustedRelayerIsm
interchainAccountRouter:
  address: "0x76D0492907c8Cb0039C090C044767289B2cb8DFF"
  commitmentIsm:
    address: "0x8D53870dFce2C70b19D4dBaD27C10BEDD69B8c79"
    owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
    type: offchainLookupIsm
    urls:
      - https://commitment-read-ism.hyperlane.xyz
  hook: "0x0000000000000000000000000000000000000000"
  interchainSecurityModule:
    address: "0x76D0492907c8Cb0039C090C044767289B2cb8DFF"
    isms: {}
    owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
    type: interchainAccountRouting
  mailbox: "0xaf27F006C81fdE2D876282Cd6Cb370338d73B246"
  owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  remoteRouters: {}
owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
proxyAdmin:
  address: "0xFC31aE61939cD0dBC821BE14c12F1c2f3Be32666"
  owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
requiredHook:
  address: "0x0cbA133d244f505A4A745BB0b9bAD38e001B8e7A"
  hooks:
    - address: "0xcF0D4A3008d5DE1049094d20EEb31d2344541E8e"
      beneficiary: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
      oracleConfig:
        bsctestnet:
          gasPrice: "100000000"
          tokenDecimals: 18
          tokenExchangeRate: "10000000000"
        kasplextestnet:
          gasPrice: "1000000000"
          tokenDecimals: 18
          tokenExchangeRate: "10000000000"
      oracleKey: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
      overhead:
        bsctestnet: 0
        kasplextestnet: 0
      owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
      type: interchainGasPaymaster
    - address: "0xfadA6894bF13b53048E0CA6Ea5698F2fE81292f2"
      beneficiary: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
      maxProtocolFee: "100000000000000000000000000000000000"
      owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
      protocolFee: "100000000000000000000000000000000000"
      type: protocolFee
  type: aggregationHook

